/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 26 09:35:40 GMT 2023
 */

package evo.io.cocoon.spi.util;

import org.junit.Test;
import static org.junit.Assert.*;
import io.cocoon.spi.util.ClassUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClassUtil_ESTest extends ClassUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ClassLoader classLoader0 = ClassUtil.getClassLoader(class0);
      assertNotNull(classLoader0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClassUtil classUtil0 = new ClassUtil();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtil.getClassLoader();
      assertNotNull(classLoader0);
  }
}
